//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__sum_float64(SB), $56-24

    MOVQ buf+0(FP), DI
    MOVQ len+8(FP), SI
    MOVQ res+16(FP), DX
    ADDQ $8, SP

     // mov	qword [rsp + 40], rdi
     // mov	dword [rsp + 36], esi
     // mov	qword [rsp + 24], rdx
     // vxorps	xmm0, xmm0, xmm0
     // vmovsd	qword [rsp + 16], xmm0
     // mov	dword [rsp + 12], 0
LBB0_1:
     // mov	eax, dword [rsp + 12]
     // cmp	eax, dword [rsp + 36]
	JGE LBB0_4
     // mov	rax, qword [rsp + 40]
     // movsxd	rcx, dword [rsp + 12]
     // vmovsd	xmm0, qword [rax + 8*rcx]
     // vaddsd	xmm0, xmm0, qword [rsp + 16]
     // vmovsd	qword [rsp + 16], xmm0
     // mov	eax, dword [rsp + 12]
     // add	eax, 1
     // mov	dword [rsp + 12], eax
	JMP LBB0_1
LBB0_4:
     // vmovsd	xmm0, qword [rsp + 16]
     // mov	rax, qword [rsp + 24]
     // vmovsd	qword [rax], xmm0
    SUBQ $8, SP
    RET
