// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rt

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__isspace      = __native_entry__() + 13
    _subr__u32toa_small = __native_entry__() + 52
)

const (
    _stack__isspace = 8
    _stack__u32toa_small = 8
)

var (
    _ = _subr__isspace
    _ = _subr__u32toa_small
)

const (
    _ = _stack__isspace
    _ = _stack__u32toa_small
)
